apiVersion: apps/v1
kind: Deployment
metadata:
  name: viatabloid-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: viatabloid-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
